### ISSUE TITLE
Getting Width = 0 and Height = 0 in canvas. Impossible to draw

### ISSUE THREAD

**Issue by ydakilux** [inquid/yii2-signature#1]
I'm getting the following code in my page in the browser  : 

```
<div class="signature-pad--body">
                <canvas style="touch-action: none;" width="0" height="0"></canvas>
</div>
```

I added some console ouptut into your code  of the function resizeCanvas: 

    // This part causes the canvas to be cleared
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);

    console.log('Width ' + canvas.width);
    console.log('Heigth ' + canvas.height);
    console.log('ratio ' + ratio);
    console.log('offsetWidth ' + canvas.offsetWidth);
    console.log('offsetHeigth ' + canvas.offsetHeight);

And the result in the console is : 
   Width 0
   Heigth 0
   ratio 1.5
   offsetWidth 0
   offsetHeigth 0

 I don't know why I'm getting the offsetWidth and offsetHeight => 0
 I tried with Firefox and Chrome, both the latest version
I tryed on 2 differents screen. On the biggest screen I'm getting ratio 1.5, on the other one with an 1920x1200 resolution, I'm getting ratio 1.0. That's the only différence

   Thanks by advance

**Comment by ydakilux** [comment]
I found a small solution adding the following code on my page : 

Adding the following code into app.js after resizecanvas() solved my problem

```
document.addEventListener("DOMContentLoaded", function() {
    resizeCanvas();
});
```

**Comment by gogl92** [comment]
Hi I will check it late today, and update if needed. :)
